### ISSUE TITLE
WAL: Cliente indica que el acs esta causando reinicios de las onts.

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#111]
Según WAL krill esta causando reinicios aleatorios de las onts, con las quejas de los clientes que eso genera. 

ont para testear:485754435a3bb2a6

**Comment by jgmel** [comment]
Que ficha más rara... y sin JS errors
![image](https://user-images.githubusercontent.com/15957090/185865764-93722470-71a7-4592-a977-2792b1fdaf0a.png)

**Comment by Andresphicus** [comment]
@rpardines había un log de una ONT que hacia referencia a que la ONT se quejaba de que se había reiniciado por el ACS no?
puedes pasarlo o poner el log de esa ONT?

**Comment by rpardines** [comment]
acaban de añadir el cpe0151, donde se aprecia un reincio y muchisimos periodic inform

**Comment by jgmel** [comment]
Problema localizado, ocurre con CPE con `enable_notificacion` activado. En estos clientes bajamos el periodic inform a 15 min
```
{% if host.notifications_enabled %}
InternetGatewayDevice.ManagementServer.PeriodicInformInterval: 900
{% else %}
```
En krill 1 el action reboot se envia tanto por gpon omci como por ACS. El ACS tiene un timeout de 120 segundos, si el inform entra en este tiempo lo reiniciamos provocando un doble reboot. No he podido localizar nigún reboot anomalo

De momento he subido el PeriodicInformInterval manulmante a 2 Horas en los CPE con `enable_notificacion`

**Comment by jgmel** [comment]
@rpardines alguna novedad? Entre vacas... leí que el cliente solicito desactivar el ACS en todos los CPE's

**Comment by rpardines** [comment]
El cliente no atiende a razones y sigue pensando que el ACS es el culpable.
