### ISSUE TITLE
MELKOR: deja de enviar notificaciones y no esta accesible

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#112]

**Comment by jgmel** [comment]
Melkor (melkor.phicus.es) ya no esta accesible se desabilitó en favor de [heimdall](https://heimdal.phicus.es/). Le hago una redirección para los nostalgicos...

**Comment by jgmel** [comment]
Redirección realizada, ahora [melkor.phicus.es](https://melkor.phicus.es) apunta a [heimdal](https://heimdal.phicus.es/)

**Comment by rpardines** [comment]
Volveran a llegar las alarmas al canal del cliente con origen melkor¿?

**Comment by jgmel** [comment]
Supongo que toca personalizar el `var.slack_token` del Host o Servicio correspodiente con el token de slack del cliente  ¿@Andresphicus correcto?

**Comment by Andresphicus** [comment]
pues tengo que ver como estaba montando en Shinken (no tengo ni ida)
y montarlo

**Comment by Andresphicus** [comment]
Testing, 
Se hará de forma dinamica, la plantilla de notificaciones tiene en cuenta el Slack_api_token del ADMIN.yml de cada Host para enviar la notificación
En principio se han reactivado las que estaban
- Caida de un servidor
- Perdida de SSH
- Caida de las redes publicas del operador 
@rpardines cualquier cosa nos avisas

**Comment by Andresphicus** [comment]
Commit -> https://github.com/phicus/ansible-phicus/commit/6b37565c77631bd1e8ca89aa06add758932204a2
