### ISSUE TITLE
Numero total de CPE online en K2 puede inducir a error

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#118]

**Comment by rpardines** [comment]
Los clientes que usan Krill2 y compran el numero total de cpes con K1, tienen dudas por el descuadre de cpe:
https://cbv.phicus.es/monitoring/host-groups
http://cbv.phicus.es:4267/hosts-groups

**Comment by jgmel** [comment]
Algo más de info?

**Comment by rpardines** [comment]
como esta coincidiendo con un cambio de olt. estamos a la espera de que se actualicen los datos y se borren duplicados

**Comment by SerialKriller** [comment]
Lo hemos estado repasando, en realidad sí cuadran los números si tenemos en cuenta que los clientes de Antuco salen por Quilleco y dependen de él, por tanto Krill en el smartree los pinta como número de Quilleco, hemos hecho la suma y al final los clientes dan en número.
Eso y que ayer había ONUs duplicadas, unas 100 que hemos borrado esta mañana

**Comment by paveldelpozo** [comment]
@rpardines @SerialKriller Entonces esta tarjeta se puede dar por cerrada?

**Comment by rpardines** [comment]
si
