### ISSUE TITLE
Krill2:   ficha monitor limita el acceso a contenido por contactgroup. de igual manera que en krill1

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#17]

**Comment by Andresphicus** [comment]
Se opta por hacer host groups específicos para cada uno de los contact_groups de inventario y para cada realm de forma independiente
de este modo, sesteando el permiso del HG que toque, ejemplo, NOC, o TST (en lab) , tendrá solo a los hosts que tengan en ese contacto group vinculado 
Funcionando en LAB

**Comment by Andresphicus** [comment]
Funcionando en GAR también

**Comment by rpardines** [comment]
Puedes probar en fbn?

**Comment by Andresphicus** [comment]
si claro @rpardines 
lo quieres ya o para la semana que viene?
