### ISSUE TITLE
Check Ifaces falla en redes que estan correctas

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#22]
Tras ir migrando paulatinamente todas las redes a usar netplan, nos encontramos que por ejemplo CAL,ALO,CRT el check_ifaces deja de funcionar debido a este error.

**Comment by rpardines** [comment]
![image](https://user-images.githubusercontent.com/32762171/166413017-b972f686-c3ac-4fc4-81b3-3de925f78fda.png)

**Comment by rpardines** [comment]
Se incluye Ite1 e Ite2 al error

**Comment by johnnyfontana** [comment]
Resuelto lo de ite1 e ite2, ya que no se contemplaba para la opción `to` de una ruta la opción `default`. Para ello, se usaba `0.0.0.0`. Ahora ya también se contempla.

En cuanto a ALO, CAL y CRT, o mal formateo del yaml o que interfería el fichero `50-cloud-init.yaml`, cuando el que hemos decidido usar es network-config.yaml. Borrado y listo
