### ISSUE TITLE
Validador de versiones instaladas en servidor

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#26]
Como paso final al proceso de deploy. Seria necesario disponer de una herramienta que nos permita checkear de manera rápida que las versiones  instaladas tras un deploy son las esperadas. Evitando así que redes tengan modulos no actualizados.

**Comment by rpardines** [comment]
Hoy se produjo incidencia en stp, motivo:Core con version antigua

**Comment by jgmel** [comment]
¿Esto existe? En caso afirmativo, como se usa?

**Comment by rpardines** [comment]
es una necesidad, poder realizar como el check ifaces para todos los servidores. lo mismo y que muestre modulos instalados

**Comment by Andresphicus** [comment]
De primeras se hará con Kiwi

**Comment by rpardines** [comment]
Y no puede lanzarse un check global de k2?

**Comment by Andresphicus** [comment]
Juan da una pista: https://phicus.slack.com/archives/CCJTASNKD/p1657535881326699
Si, Raul, habrá un check global o en Heimdal o en K2, disponible, esa es la idea

**Comment by Andresphicus** [comment]
Funcionando en Heimdal -> https://heimdal.phicus.es/monitoring/all?search=service%3Akrill_versions
cualquier cosa nos decís @rpardines 
De momento se comprueban estos paquetes
```
KRILL_PACKAGES = [
    "kiwi",
    "django-icinga",
    "krill-acs",
    "krill-core",
    "krill-docsis3",
    "krill-gpon",
    "krill-oratio",
    "krill-wimax",
    "libkrill",
]
```

**Comment by rpardines** [comment]
Por lo pronto, ¿Como procedemos para homogeneizar todos y reducir el numero de alarmas?

**Comment by Andresphicus** [comment]
Desplegando 😂

**Comment by rpardines** [comment]
Ok, pues añade a tu sprint que el proximo martes hay que homogeneizar todo. Creo tarjeta en github

**Comment by Andresphicus** [comment]
funcionando y desplegado en Heimdal 
la cierro, está no hay que llevarla a los operadores
