### ISSUE TITLE
Krill2:en krill2  no se insertan  las mac FC:EC:DA:90:E3:53 hay que ponerlas como FCECDA90E353. queja de cliente en MOW.

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#27]

**Comment by paveldelpozo** [comment]
El error no es por poner la mac con o sin dobles puntos, es que estaba tratando de modificar un CPE poniéndole una MAC que ya existía.

Hemos creado una tarjeta para poder mostrar correctamente los errores devueltos por la API: https://github.com/phicus/krill-isp-ui/issues/32

Cierro esta tarjeta
