### ISSUE TITLE
La lupa de Kiwi no muestra los cpes pendientes de provisionar

### ISSUE THREAD

**Issue by johnnyfontana** [phicus/krill#36]
http://gar.phicus.es:4280/api/v2/gpon/unconfigured/ devuelve un "403 Forbidden"

Comprobado en varios operadores distintos, tanto beta como normales

**Comment by johnnyfontana** [comment]
Problema de validación de ip en el nginx.

**Comment by jgmel** [comment]
Un `./kws.yml -t nginx` es tu amigo
