### ISSUE TITLE
Activar nuevo provisionador GOU y ART

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#37]
¿esto no es cosa de inventario?

**Comment by jgmel** [comment]
Si, @rpardines cerramos?

**Comment by jgmel** [comment]
ok

**Comment by Andresphicus** [comment]
@johnnyfontana @rpardines 
creo que gou ya está
Art según veo tb 
¿cerramos?

**Comment by johnnyfontana** [comment]
Se puede cerrar
