### ISSUE TITLE
GOU:quejas reiteradas y repetidas de clientes por fallo en matrix

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#56]
https://phicus.slack.com/archives/G5LDBFGDB/p1656311383956639

**Comment by rpardines** [comment]
https://phicus.slack.com/archives/G5LDBFGDB/p1656311383956639

**Comment by paveldelpozo** [comment]
Related with:

- [ ] https://github.com/phicus/django-icinga/issues/137
