### ISSUE TITLE
ACS: provisión ont ZTE para SNL

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#61]

**Comment by rpardines** [comment]
El cliente nos facilita anydesk

Usario:
340591980
Pass:
Pc@SVT_Pdro1

Para acceso al Router de SuperAdmin:
Usuario: Sup3r4dm1n
Pass: !Adm1nH()m1x$Un1d4t4!

**Comment by rpardines** [comment]
pues una fecha de expiración para el proximo 4 de julio ampliable hasta el 8

**Comment by paveldelpozo** [comment]
Close as duplicate: https://github.com/phicus/krill-acs-templates/issues/13
