### ISSUE TITLE
ACS: integración modelos CDATA para OLI

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#64]

**Comment by rpardines** [comment]
Continuación de la tarea:
https://opteam.phicus.es/web#id=544&action=84&model=opteam.task&view_type=form&cids=1&menu_id=69

**Comment by Andresphicus** [comment]
esto está cerrado ya

**Comment by Andresphicus** [comment]
a la espera de que ellos nos pongan más equipos para proabr
