### ISSUE TITLE
MTV: gran cantidad de bugs en Krill2

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#71]

**Comment by rpardines** [comment]
En el dasboard le salen a veces problemas como este de un cpe y en cambio el cpe está perfecto:


![Image](https://user-images.githubusercontent.com/32762171/176664886-6963a273-da78-4887-97d0-24f2695cc86d.png)



![Image](https://user-images.githubusercontent.com/32762171/176664916-4ad52ed0-42c9-4b5a-abab-6b2e5e6fe042.png)

 2. No se pueden hacer reset a fábrica desde la ficha monitor de los cpes



![Image](https://user-images.githubusercontent.com/32762171/176664988-5958aa13-d493-4df9-b86f-d74816ded8fd.png)

3.  cpe pppoe de wimax que en la ficha monitor le sale una ip y luego en oratio le pone la que verdaderamente tiene 



4. Esto está bajo investigación aún, pero a  muchas ont zte f670L no entramos por proxy, lo raro aquí es que no cazamos que puede ser el problema porque algunas van y otras no (estoy sacando un listado grande de pruebas)  .,,,este punto en tejado operaciones

**Comment by rpardines** [comment]
En la vista Matrix no aparece la ip lan del cpe. como si aparece en shinken

**Comment by Andresphicus** [comment]
Problema 1: las olts no se estaban monitorizando de forma correcta, creo que está resuelto
Problema 2: lo del factory, creo que está ya resuelto, cualquier cosa nos decis
Problema 3: tb está resuelto, no se quien se encargo, pero veo que la información aparece de forma correcta:
https://mtv.phicus.es/monitoring/host/cpe16340/services/pppoe/
Problema 4: estaba en vuestro tejado, creo que era algo de Antonio y que ha quedado resuelto

**Comment by Andresphicus** [comment]
@jgmel abrimos tarjeta para ver lo de la IP en Matrix?

**Comment by rpardines** [comment]
¿y sobre el 5?

En la vista Matrix no aparece la ip lan del cpe. como si aparece en shinken

**Comment by jgmel** [comment]
> @jgmel abrimos tarjeta para ver lo de la IP en Matrix?

Si, a ver si se hace vía address o customvar

**Comment by Andresphicus** [comment]
para lo de la IP lan lanzo nueva tarjeta: https://github.com/phicus/ansible-phicus/issues/460
