### ISSUE TITLE
Krill2: No se pueden realizar tareas por lotes desde isp

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#72]

**Comment by rpardines** [comment]
De la misma manera que en Krill1 un operacor podia cambiar un cliente o varios por ejemplo el tipo de direccionamiento, es decir de publica a nateada. Esta función no es posible en Krill2

**Comment by paveldelpozo** [comment]
@rpardines Podrías especificar cuales son todas las tareas por lotes que os interesaría tener? Entiendo que son a nivel de la vista CPE

**Comment by rpardines** [comment]
![image](https://user-images.githubusercontent.com/32762171/177951710-6d5d6fad-965c-4044-abae-9b055b3ca088.png)

concretamente todas esas y si puedes añadir alguna otra de utilidad seria de agradecer

**Comment by jgmel** [comment]
Creo que el `line_profile` y el `profile` (perfil de velocidad) también es útil para cambiar, los clientes ha pedido varias veces hacer esos cambios de forma masiva

**Comment by rpardines** [comment]
Correcto

**Comment by rednach** [comment]
fire?

**Comment by jgmel** [comment]
No creo, bajo prioridad

**Comment by jgmel** [comment]
> Pero tendremos algo la semana proxima?

Ya se está trabajando en https://github.com/phicus/krill-ws/issues/257
