### ISSUE TITLE
AVT: CPE wimax status fail in icinga

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#78]

**Comment by SerialKriller** [comment]
Pongo ejemplo práctico que facilita entender el bug.

Tenemos un AP DOWN unas 15 horas.

![Image](https://user-images.githubusercontent.com/22931588/177960699-4a26ccc5-0e57-4054-aeac-6cdeeae652a4.png)

Tenemos los CPEs down en su ficha **desde el momento que entras a la ficha a ver su estado:**

![Image](https://user-images.githubusercontent.com/22931588/177960894-b9c0eff7-6df8-441a-b414-2bdbef74c1d0.png)

Pero en cualquier búsqueda de Krill o vista que no sea la ficha, todos los CPEs registrados en el host padre, o sea, el AP, están UP:

![Image](https://user-images.githubusercontent.com/22931588/177961122-b9130411-25d5-4cb7-8686-6240986e2dc2.png)

**Comment by Andresphicus** [comment]
to deploy
```
icinga2.yml -t basket
```

**Comment by Andresphicus** [comment]
Prueba de funcionamiento
https://avt.phicus.es/monitoring/host/cpe28443
