### ISSUE TITLE
INN: en K2 no se muestran las frecuencias correctas de los cablemodems

### ISSUE THREAD

**Issue by rpardines** [phicus/krill#81]
Tomando como ejemplo el CPE34976:
https://inn.phicus.es/monitoring/host/cpe34976/services/downstream/
se registran correctamente los descendentes, pero no los graficamos
https://inn.phicus.es/monitoring/host/cpe34976/technology
induce a error, ya que muestra otras frecuencas, las cuales el cablemodem no esta usando:
https://10.22.12.176.inn.phicus.net/cgi-bin/event_cgi

**Comment by rpardines** [comment]
Tomando como ejemplo el CPE34976:
https://inn.phicus.es/monitoring/host/cpe34976/services/downstream/
se registran correctamente los descendentes, pero no los graficamos
https://inn.phicus.es/monitoring/host/cpe34976/technology 
induce a error, ya que muestra otras frecuencas, las cuales el cablemodem no esta usando:
https://10.22.12.176.inn.phicus.net/cgi-bin/event_cgi

**Comment by jgmel** [comment]
@rpardines  convierto tu comentario en la descripción del issue

**Comment by Andresphicus** [comment]
esto está duplicado, 
en principio está resuelto en : https://github.com/orgs/phicus/projects/9/views/21
y desplegado en INN
cierro,
